project:
  title: "rzine-template"

lang: fr-FR  
language: _language.yml # sert à modifier le nom de la partie "téléchargements"

draft: true      # sur HTML : bandeau en haut ; sur PDF : “Brouillon” en biais (à modifier dans before-body.tex)
published: false # utile car le bloc div est commenté dans title-metadata.html ?
repo: "template" # à définir ? c'est aussi commenté dans title-metadata

title: "Rzine mis en application avec R"
subtitle: "Articles méthodologiques mis en application avec R Articles méthodologiques mis en application avec R"
date: today
# date-modified: last-modified

author:
  - name: "Auteur·rice 1"
    url: "https://rzine.fr"
    affiliations:
      - name: "Etablissement 1"
        url: "https://xxxxx.fr"
    orcid: 0000-0000-0000-0000

  - name: "Auteur·rice 2"
    url: "https://rzine.fr"
    affiliations:
      - name: "Etablissement 2"
        url: "https://xxxxx.fr"
    orcid: 0000-0000-0000-0000
  
  - name: "Auteur·rice 3"
    url: "https://rzine.fr"
    affiliations:
      - name: "Etablissement 3"
        url: "https://xxxxx.fr"
    orcid: 0000-0000-0000-0000
    
keywords: 
  - Rzine
  - template
  - Quarto
  - méthodes
  - R
  - reproductbilité
  - outils
  - géomatique
  - base de données

abstract: |
     Modèle de mise en page Quarto pour la revue Rzine, qui permet de publier sur des méthodes de SHS, mises en application avec R. Plus d'informations sur [https://rzine.fr](https://rzine.fr).

doi: "10.xxxx/xxx-xxx"

other-links:
  - text: Code source
    icon: github
    href: "https://github.com/rzine-reviews/rzine-article-template"

format:
  Article-html: default
  Article-pdf: default



